/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssetCreateNestedManyWithoutProductsInput } from "./AssetCreateNestedManyWithoutProductsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { CategoryCreateNestedManyWithoutProductsInput } from "./CategoryCreateNestedManyWithoutProductsInput";
import { OrderCreateNestedManyWithoutProductsInput } from "./OrderCreateNestedManyWithoutProductsInput";
@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: () => AssetCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => AssetCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => AssetCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  assets?: AssetCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => CategoryCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CategoryCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CategoryCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  categories?: CategoryCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  itemPrice?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutProductsInput;
}
export { ProductCreateInput };
